version: '3'

tasks:
    default:
        dir: .
        cmds:
            - go mod download
            - go mod tidy
            - go mod verify
            - go fmt .
            - go vet .
            - go clean .
            - task: build
            - ./dist/modelhub_linux_amd64_v1/modelhub
        silent: false

    go_build:
        - rm -rf ./build
        - mkdir ./build
            - go build -o ./build ./cmd/modelhub
        - ./build/modelhub list --table | head -5

    build:
      - goreleaser --snapshot --clean

    cross-build:
      cmds:
        - mkdir -p dist
        - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o dist/modelhub_linux_amd64 ./cmd/modelhub
        - GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o dist/modelhub_linux_386 ./cmd/modelhub
        - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o dist/modelhub_linux_arm64 ./cmd/modelhub
        - GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=0 go build -o dist/modelhub_linux_armv6 ./cmd/modelhub
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o dist/modelhub_linux_armv7 ./cmd/modelhub
        - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o dist/modelhub_darwin_amd64 ./cmd/modelhub
        - GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o dist/modelhub_darwin_arm64 ./cmd/modelhub
      silent: false

    install-hooks:
        cmds:
#            - pip install pre-commit
#            - pip install --upgrade pre-commit
            - pre-commit install
    remove-hooks:
        ignore_error: true
        cmds:
            - pre-commit uninstall
            - rm .git/hooks -rf
